98 refactor openid4vc library 2
walt-id/waltid-identity pull request #804
Opened 2024-10-18 09:18 UTC by severinstampler

## Description

Provide a clear and concise description of the changes made in this pull request:

Refactoring of Issuer OpenID4VCI backend functionality. Removal of abstract class implementations etc.

## Type of Change

- [ ] bug fix - change which fixes an issue
- [ ] new feature - change which adds functionality

## Checklist

- [ ] code cleanup and self-review
- [ ] unit + e2e test coverage
- [ ] documentation updated accordingly

## Breaking

- \-

2024-10-22 08:15 UTC, chsavvaidis requested changes

2024-10-23 07:58 UTC, taminobaumann submitted a review, later dismissed

2024-10-23 08:48 UTC, severinstampler commented on waltid-libraries/protocols/waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/OpenID4VCI_Test.kt
> +  @Test
tests cover full auth flow and pre-authorized auth flow

2024-10-23 08:49 UTC, severinstampler commented on waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/OpenID4VC.kt
> +object OpenID4VC {
needs updating

2024-10-23 09:02 UTC, taminobaumann approved these changes

2024-10-23 09:10 UTC, closed without merging